name: RSpec

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    # services:
    #   db:
    #     image: mariadb:latest
    #     env:
    #       MYSQL_ROOT_PASSWORD: password
    #       MYSQL_DATABASE: root
    #     ports:
    #       - 3306:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    services:
      mysql:
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: root
          BIND-ADDRESS: 0.0.0.0
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show MySQL Logs
        run: |
          docker logs ${{ job.services.mysql.id }}

      # ソケットを確認
      - name: Show MySQL socket information
        run: |
          docker exec ${{ job.services.mysql.id }} ls -la /var/run/mysqld/

      - name: Show running MySQL processes
        run: |
          docker exec ${{ job.services.mysql.id }} ps aux

      - name: Confirm MySQL is running
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            sleep 1
          done

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      # - name: Setup MariaDB
      #   shell: bash
      #   env:
      #     MYSQL_DATABASE: testdb
      #   run: |
      #     docker-compose up -d

      - name: Run RSpec
        run: |
          cd back
          bundle install
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rspec
